project:
  type: website
  output-dir: docs

website:
  title: "Quant research notebooks"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    number-sections: false
    self-contained: true
    fig-width: 10
    fig-height: 6
    fig-dpi: 150
    df-print: kable
    page-layout: article
    mainfont: "Calibri, Arial, Helvetica, sans-serif"
    monofont: "Consolas, Courier New, Monospace"
    fontsize: "11pt"

execute:
  enabled: true
  echo: false
  warning: false
  error: false
  freeze: auto

# Metadata
metadata:
  author: "Vivian Chua"
  date: today
  date-format: "D MMM YYYY"